events {}
http {
 upstream fe { server frontend:80; }
 upstream be { server backend:8000; }
 server {
   listen 80;
   location /api/ { proxy_pass http://be; proxy_set_header Host $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; }
   location / { proxy_pass http://fe; proxy_set_header Host $host; }
 }
}